In [4]:
#Take an input matrix with size 5x5 and a kernel with size 3x3, perform convolution with stride being 1 and 2.

import numpy as np


# take input matrix with size 5x5
input_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("Input matrix is: ")
for i in range(5):
    for j in range(5):
        print(input_matrix[i][j], end = " ")
    print()

# take kernel with size 3x3
kernel = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Kernel is: ")
for i in range(3):
    for j in range(3):
        print(kernel[i][j], end = " ")
    print()

# perform convolution with stride being 1
print("Convolution with stride being 1 is: ")
for i in range(3):
    for j in range(3):
        print(sum(sum(input_matrix[i:i+3,j:j+3]*kernel)), end = " ")
    print()

# perform convolution with stride being 2
print("Convolution with stride being 2 is: ")
for i in range(0,5,2):
    for j in range(0,5,2):
        print(sum(sum(input_matrix[i:i+3,j:j+3]*kernel)), end = " ")
    print()
# save the result to a numpy array
np.save('result.npy', input_matrix)
# load the numpy array
result = np.load('result.npy')
print(result)



Input matrix is: 
1 2 3 4 5 
6 7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 
21 22 23 24 25 
Kernel is: 
1 2 3 
4 5 6 
7 8 9 
Convolution with stride being 1 is: 
411 456 501 
636 681 726 
861 906 951 
Convolution with stride being 2 is: 
411 501 540 
861 951 990 
996 1086 1125 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [5]:
# Apply max-pooling, average-pooling and sum-pooling to the results from above convolutions

def max_pooling(result):
    # max pooling
    print("Max pooling is: ")
    for i in range(0,3,2):
        for j in range(0,3,2):
            print(max(max(result[i:i+2,j:j+2])), end = " ")
        print()
max_pooling(result)

Max pooling is: 


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()